pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                bat script: '''
                    echo "----------------------------------- Build Step Started -----------------------------------"
                    gradlew build
					echo "----------------------------------- Build Step Completed -----------------------------------"
                ''',
            label: "Building Project"
            }
        }
        stage('Test')
        {
            steps {
                bat script: '''
                    echo "----------------------------------- Tests Step Started -----------------------------------"
                    gradlew test
					echo "----------------------------------- Tests Step Completed -----------------------------------"
                ''',
            label: "Running Unit Test Cases"
            }
        }
        stage('Static Code Analysis')
        {
            steps {
                bat script: '''
                    echo "----------------------------------- Sonarcube Step Started -----------------------------------"
					echo "#TODO Sonarcube Scan"
					echo "----------------------------------- Sonarcube Step Completed -----------------------------------"
                ''',
            label: "Running Sonarqube Scan"
            }
        }
        stage('Build DockerImage')
        {
            steps {
                bat script: '''
                    echo "----------------------------------- Build DockerImage Step Started -----------------------------------"
					docker build -t "mars-rover-container" -f .infra/docker/Dockerfile .
					docker run mars-rover-container
					echo "----------------------------------- Build DockerImage Step Completed -----------------------------------"
                ''',
            label: "Building Docker Image"
            }
        }
        stage('Publish DockerImage')
        {
            steps {
                bat script: '''
                    echo "----------------------------------- Publishing DockerImage Step Started -----------------------------------"
					docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
					docker tag mars-rover-container bsvishal123/mars_rover_container:first
					docker push bsvishal123/mars_rover_container:first
					echo "----------------------------------- Publishing DockerImage Step Completed -----------------------------------"
                ''',
            label: "Publishing Docker Image"
            }
        }
    }
}